### ISSUE TITLE
Profile: make protips the first view when viewing profile

### ISSUE THREAD

**Issue by kitsunde** [coderwall/coderwall-next#19]
The core mechanic of coderwall is posting pro-tips, I use it for note taking. Achievements is more a meta-thing.

**Comment by mdeiters** [comment]
Likely yes. I'm working on making it easier to discover protips and new ones. Once those updates are done and collect a little more feedback we can move to feature protips more.

**Comment by mdeiters** [comment]
@kitsunde I'm a little late to this but we've finally rolled out that change. Hope you like it! (see https://coderwall.com/celc)
