### ISSUE TITLE
Protips: improve SEO with unique meta tag descriptions

### ISSUE THREAD

**Issue by mdeiters** [coderwall/coderwall-next#22]
90% of coderwall traffic comes from SEO. The protips descriptions are very repetitive which Google doesn't like "A protip by xxx about tag1, tag2, tag3". Not sure the best approach but we need better, more unique descriptions

**Comment by mdeiters** [comment]
Here are some ideas worth exploring:
* http://techoctave.com/c7/posts/42-create-your-blog-post-meta-description-automatically-in-rails/
* https://coderwall.com/p/dnnlea/how-to-truncate-a-string-that-s-markdown-format

**Comment by whatupdave** [comment]
Given the recent SEO improvements, is this still relevant @mdeiters?

**Comment by mdeiters** [comment]
closing
