### ISSUE TITLE
Change path of users#show from /:username to /u/:username

### ISSUE THREAD

**Issue by seuros** [coderwall/coderwall-next#24]
Currently we use allow users to have their usename in the root path. That force us to use a blacklist to restrict users from using usernames that conflict with other paths such as /faqs/ /tos/ ect.

I think we should move this to /u/:username instead.

**Comment by polurupraveen** [comment]
sounds reasonable.

**Comment by mdeiters** [comment]
This would break SEO though, we'd have to retain the /:username for awhile...
