### ISSUE TITLE
Enable one-off marketing emails to announce features/news to entire user base.

### ISSUE THREAD

**Issue by mdeiters** [coderwall/coderwall-next#27]
Goal is to quickly send one-off marketing emails to the entire Coderwall community. We currently use postmark for this but they are only priced for transactional email. I think send grid could be a good alternative for this but we need:

* A generic template
* Place to write content for a marketing email
* Ability to trigger sending email via rake task or some other process

**Comment by whatupdave** [comment]
Did you want to switch away from postmark completely? Or are you happy with using a different email domain for marketing emails?

**Comment by mdeiters** [comment]
Up to you, i did all the work to get postmark working for transactional emails (SPF records, etc) but its a shame its not useable for marketing. Open to keeping them separate or consolidating.
