### ISSUE TITLE
New Contribution Guidelines??

### ISSUE THREAD

**Issue by andela-oakinniranye** [coderwall/coderwall-next#34]
I visited the `coderwall-legacy`, hoping to find a way to contribute however the Assembly has been discontinued since Dec 2015. I was wondering when the CONTRIBUTING.md would be updated to reflect new guidelines for contribution. Also I'd like to contribute to the `coderwall-next`, I'd appreciate the new guidelines for contributing.

**Comment by tyrollins** [comment]
As would I, I'm keen to get involved.

**Comment by mdeiters** [comment]
Thanks for raising this issue. I just started a CONTRIBUTING file. We'll continue to add to it over time too.
