### ISSUE TITLE
BUG: New Job form - Optional company logo is not so optional

### ISSUE THREAD

**Issue by codebender** [coderwall/coderwall-next#36]
I was blocked from posting a Job because there was no company logo set.  The label says it is optional, perhaps we should remove the _optional_ or fix the bug with the react component

![image](https://cloud.githubusercontent.com/assets/987305/15987703/90efbff4-2fef-11e6-8e66-cce2c14d2682.png)

**Comment by mdeiters** [comment]
Good catch. Let's fix it by removing the bug - making it actually optional :D

**Comment by andela-oakinniranye** [comment]
Taking a stab at this. Quick confirmation though, if a logo was selected but not valid, I think it makes sense to still highlight the error to the user, right?
