### ISSUE TITLE
Delete account not working

### ISSUE THREAD

**Issue by altern8tif** [coderwall/coderwall-next#38]
After visiting `http://coderwall.com/delete_account` when logged in, there is no trash icon next to the edit button that allows me to delete the account.

Please advise the necessary actions that I need to delete my account.

**Comment by andela-oakinniranye** [comment]
What should happen on the `delete_account`? I'm not totally clear on what is expected to happen, but I'd love to submit a PR for the fix!

**Comment by andela-oakinniranye** [comment]
@mdeiters @seuros Could this be for deleting a user's account?

**Comment by whatupdave** [comment]
Closing this in favor of #43

**Comment by stephenirven** [comment]
#43 is also closed and locked. This is still not working.

**Comment by whatupdave** [comment]
Thanks @stephenirven i'll take a look at this tonight

**Comment by pitrT** [comment]
Any update on this? Currently trying to delete my account, but it's not working.

**Comment by bitcrumb** [comment]
+1

**Comment by ShanikaEdiriweera** [comment]
Delete account button with the url https://coderwall.com/delete_account is not working

**Comment by JorgeBucaran** [comment]
Ping @whatupdave. Can you delete my account too please?
