### ISSUE TITLE
delete_account should delete the user and all their data

### ISSUE THREAD

**Issue by andela-oakinniranye** [coderwall/coderwall-next#43]
From #38 I tried to check the `/delete_account` route and yes I can confirm nothing happens.  But I was wondering what was supposed to happen on the route? Should we delete the user's account? Should we use a gem like `paranoid` to mark the user as deleted, for application integrity? I think using `paranoid` or similar solution works best though.

**Comment by whatupdave** [comment]
I think it would be best to scrub personal data and mark the user as deleted. Not sure if a gem is required here.

**Comment by mdeiters** [comment]
Hey @andela-oakinniranye - good question - I think your hunch to user paranoid is reasonable but given our user base, it is ofter their wishes to not have any trace of data remaining. I'd rather error on the side of what they want so I'm good with just deleting all their data;  it currently does so when an admin clicks it. I guess we somehow lost the ability for users to delete their own account.

**Comment by mbmccormick** [comment]
Is there an ETA for a fix? Also would like to delete my account and emails to support@coderwall.com are going unanswered.

**Comment by andela-oakinniranye** [comment]
I'd be creating a PR for this later today, however, acceptance and subsequent merging of the PR is at the discretion of the core maintainers, therefore an accurate ETA may not be available at the moment.

**Comment by mbmccormick** [comment]
Thanks, I managed to delete it myself. In case anyone else is interested, you can do so by modifying the form in your browser: 

1. Click the Edit Profile button on your profile.
2. Inspect Element on the edit form. 
3. Change the value on the `<input type="hidden" name="_method" value="patch" />` element to `delete`. 
4. Click the Save button.

CC @MartinRogalla

**Comment by MartinRogalla** [comment]
Thank you @mbmccormick that worked for me as well. Appreciate it!
