### ISSUE TITLE
The badges I earned...

### ISSUE THREAD

**Issue by Angelfirenze01** [coderwall/coderwall-next#60]
Between 2013, when I started learning programming, and now have just plain vanished, but I've seen other profiles on Coderwall who still have their badges, so I'm wondering what I need to do to get mine back.  What happened to them in the first place?

**Comment by whatupdave** [comment]
We're moving away from the badges and focusing mostly on pro-tips. Nobody works full time on Coderwall so we have to manage our time as best as we can.

**Comment by strugee** [comment]
@whatupdave this makes me sad; I was actually really really into the badges :(

I get it though. If that's the case, could you update https://coderwall.com/faq which implies that they're coming back at some point?

**Comment by whatupdave** [comment]
@strugee me too! Thanks for pointing out the FAQ, I updated it https://github.com/coderwall/coderwall-next/commit/87a3d560156760e168e3ab946ea3972bd38ce63c

**Comment by strugee** [comment]
RIP! Thanks for your work on Coderwall, @whatupdave <3

**Comment by aferiat** [comment]
@strugee  is he dead? :(

**Comment by strugee** [comment]
@aferiat ...the badges. RIP the badges :P

**Comment by aferiat** [comment]
OH MY GOD ! can you imagine i thought he was dead and was searching all the net to have confirmation ! 
i feeel so stupid right now, Thank God i was wrong and i just didnt understand your comments :( sorry dave :(

**Comment by strugee** [comment]
@aferiat hahahaha don't worry about it :'D

Text-only communication sucks sometimes!

**Comment by whatupdave** [comment]
😂 The reports of my demise are greatly exaggerated

**Comment by aferiat** [comment]
@whatupdave  im really sorry :( 
thanks again for the amazing work you do.
