### ISSUE TITLE
Remove me from your site

### ISSUE THREAD

**Issue by miguelbalparda** [coderwall/coderwall-next#61]
Hi, can you please remove my user from your site? I emailed you several times to have my name removed from your site and I couldn't get a single answer.

**Comment by Un3qual** [comment]
https://coderwall.com/faq

**Comment by kincaidoneil** [comment]
Per the FAQ, I tried clicking the trash icon and going to [https://coderwall.com/delete_account](https://coderwall.com/delete_account) multiple times; neither worked. Is this a bug?

**Comment by whatupdave** [comment]
Looks like the faq is out of date, you should be able to delete your account by clicking the trash icon on your profile page.
