### ISSUE TITLE
Using Turbolinks

### ISSUE THREAD

**Issue by justin808** [coderwall/coderwall-next#63]
Any details that you can share about your experiences with TurboLinks and ReactOnRails? 

I noticed that you have some turbolinks code in your client registration file:

https://github.com/coderwall/coderwall-next/blob/master/client/startup/clientRegistration.jsx#L19

```js
turbolinks.start()

ReactOnRails.setOptions({
  traceTurbolinks: TRACE_TURBOLINKS, // eslint-disable-line no-undef
})
```

I've mostly stopped using it because it conflicts with React-Router.

FYI, I created [React on Rails](https://github.com/shakacode/react_on_rails).

We have a bunch of [open issues regarding TurboLinks for React on Rails](https://github.com/shakacode/react_on_rails/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20turbolinks).

**Comment by whatupdave** [comment]
We're only using react to render a few things on the site so we're probably experiencing less issues with turbolinks. Thanks for react on rails! It's an awesome library. Truth be told though, I'm building future web apps in nodejs now.
