### ISSUE TITLE
Clicking delete on my own tip leads to a 404

### ISSUE THREAD

**Issue by kitsunde** [coderwall/coderwall-next#67]
On https://coderwall.com/p/u0u9cw/broccoli-babel-transpiler-is-opting-out-of-caching-on-ember i click delete and then it 404's.

<img width="920" alt="screenshot 2017-04-17 23 12 49" src="https://cloud.githubusercontent.com/assets/48965/25093135/67eb5820-23c3-11e7-9f9d-8b505d57bfcd.png">

**Comment by whatupdave** [comment]
Oh random, might be a permissions bug, i'll look into it.

**Comment by pvsukale** [comment]
I have solved this issue. pull request:

https://github.com/coderwall/coderwall-next/pull/68
