### ISSUE TITLE
When leaving a comment, the comment content isn't visible 

### ISSUE THREAD

**Issue by garcha** [coderwall/coderwall-next#71]
Repro:
1. Goto a [protip](https://coderwall.com/p/qfxp7a/host-a-static-site-on-amazon-s3-with-custom-domain-and-ssl)
2. Goto the comment section
3. Click into the comment section and type 'thanks'
The typed comment isn't visible 

<img width="1057" alt="screen shot 2017-06-19 at 10 20 26 am" src="https://user-images.githubusercontent.com/5036095/27297433-b0b530d4-54d9-11e7-94a3-feec0792eea0.png">

**Comment by asad-ali-bhatti** [comment]
It is not reproducible!
I went into comment section and wrote thanks and it is visible.

**Comment by garcha** [comment]
Looks like its working now, closing ticket.
